### ISSUE TITLE
activate plugin fails

### ISSUE THREAD

**Issue by sock3t** [VSLCatena/ldap_login#10]
When clicking the "Activate" button for the plugin I end up with this message:
```
Notice: Use of undefined constant LDAP_LOGIN_PATH - assumed 'LDAP_LOGIN_PATH' in /var/www/piwigo/plugins/Ldap_Login/maintain.inc.php on line 39

Fatal error: Uncaught Error: Call to undefined method Ldap::load_default_config() in /var/www/piwigo/plugins/Ldap_Login/maintain.inc.php:44 
Stack trace: 
#0 /var/www/piwigo/admin/include/plugins.class.php(141): Ldap_Login_maintain->install('2.2', Array)
#1 /var/www/piwigo/admin/include/plugins.class.php(181): plugins->perform_action('install', 'Ldap_Login')
#2 /var/www/piwigo/admin/plugins_installed.php(73): plugins->perform_action('activate', 'Ldap_Login')
#3 /var/www/piwigo/admin/plugins.php(46): include('/var/www/piwigo...')
#4 /var/www/piwigo/admin.php(312): include('/var/www/piwigo...')
#5 {main} thrown in /var/www/piwigo/plugins/Ldap_Login/maintain.inc.php on line 44
```
My configuration:
```
    Piwigo 2.9.4
    Operating system: Linux
    PHP: 7.0.30-0+deb9u1 (Show info) [2018-09-18 23:21:31]
    MySQL: 5.5.5-10.1.26-MariaDB-0+deb9u1 [2018-09-18 23:21:31]
    Graphics Library: GD 2.2.4
```

> Ldap_Login ver 2.2

I have tried to delete the plugin and install again but the error persists.

**Comment by decsil** [comment]
I have the same problem with the same configuration

**Comment by Kipjr** [comment]
I will immediately look into it

**Comment by Kipjr** [comment]
#11 fixed by  ce8c20d

**Comment by decsil** [comment]
It works.
Thanks for the quick help

**Comment by sock3t** [comment]
activation of the plugin works for me now. But I see these messages on top of the webpage when opening the plugin configuration (`admin.php?page=plugin-Ldap_Login-configuration`):
```

Notice: Undefined index: forgot_url in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 81

Notice: Undefined index: ldap_debug in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 82

Notice: Undefined index: host in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 83

Notice: Undefined index: basedn in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 84

Notice: Undefined index: port in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 85

Notice: Undefined index: ld_server in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 86

Notice: Undefined index: ld_attr in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 87

Notice: Undefined index: ld_group in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 88

Notice: Undefined index: ld_group_class in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 89

Notice: Undefined index: ld_group_member_attrib in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 90

Notice: Undefined index: ld_use_ssl in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 91

Notice: Undefined index: ld_bindpw in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 92

Notice: Undefined index: ld_binddn in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 93

Warning: Cannot modify header information - headers already sent by (output started at /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php:81) in /var/www/piwigo/include/page_header.php on line 101
```
This does not appear when loading the _New users when LDAP auth is successful_ page (`admin.php?page=plugin-Ldap_Login-newusers`).

**Comment by Kipjr** [comment]
Hi  Sock3t,


This behaviour is normal as data.dat isn't occupied with these values. You need to fill and save the values on the configuration page. Then, these messages will disappear.



________________________________
Van: sock3t <notifications@github.com>
Verzonden: woensdag 19 september 2018 13:36:01
Aan: VSLCatena/ldap_login
CC: Martie; Assign
Onderwerp: Re: [VSLCatena/ldap_login] activate plugin fails (#10)


activation of the plugin works for me now. But I see these messages on top of the webpage when opening the plugin configuration (admin.php?page=plugin-Ldap_Login-configuration):


Notice: Undefined index: forgot_url in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 81

Notice: Undefined index: ldap_debug in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 82

Notice: Undefined index: host in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 83

Notice: Undefined index: basedn in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 84

Notice: Undefined index: port in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 85

Notice: Undefined index: ld_server in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 86

Notice: Undefined index: ld_attr in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 87

Notice: Undefined index: ld_group in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 88

Notice: Undefined index: ld_group_class in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 89

Notice: Undefined index: ld_group_member_attrib in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 90

Notice: Undefined index: ld_use_ssl in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 91

Notice: Undefined index: ld_bindpw in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 92

Notice: Undefined index: ld_binddn in /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php on line 93

Warning: Cannot modify header information - headers already sent by (output started at /var/www/piwigo/plugins/Ldap_Login/admin/configuration.php:81) in /var/www/piwigo/include/page_header.php on line 101


This does not appear when loading the New users when LDAP auth is successful page (admin.php?page=plugin-Ldap_Login-newusers).

**Comment by sock3t** [comment]
OK, once values or filled in and saved the messages don't appear anymore.

Thanks a lot for your fast help!

Lets close this one. Running into other issues now - will file a new bug for that :)
