### ISSUE TITLE
Not possible to set initial configuration due to missing LDAP Extension

### ISSUE THREAD

**Issue by JoomlaStats** [VSLCatena/ldap_login#4]
VSLCatena, you are my hero (almost 😉),
I've been using galery menalto in the past but as this project doesn't seem to continue I was looking for an successor. As I have a few users that almost even can't remember a single uid/pw combination it's important for me that a central user authentication (LDAP) can be used.

After installation of the Ldap_Login plugin the administration -> plugins -> ldap login page (http://XXXX/admin.php?page=plugin&section=Ldap_Login%2Fadmin.php) doesn't show anything. I've been able to trace it back and also found the solution for you.

From the admin.php file the admin/configuration.php file is included.
Here the ldap_conn() function is called (defined in class.ldap.php) and then processing of the page seems to just stop.

Root cause: When the LDAP Extension is missing, then before this warning is able to be shown on the screen the pageload is aborted by line
`if ($conn = @ldap_connect($this->config['uri'])){`
in file …./plugins/Ldap_Login/class.ldap.php
in function private function make_ldap_conn()

I was able to solve this by inserting following lines just in front of that line:
```
if (!extension_loaded('ldap')) {
   print "LDAP extension not loaded<br>";
   return false;
}
```
After adding these lines the ldap_connect function is not breaking the page load anymore and the warning that explains what’s wrong is shown.

**Comment by Kipjr** [comment]
fixed using 
https://github.com/VSLCatena/ldap_login/commit/abbd74b5b68a13edef732251850a8c9b8103bc59
