### ISSUE TITLE
Long password not saved

### ISSUE THREAD

**Issue by msbt** [VSLCatena/ldap_login#5]
Hi there!
I'm trying to get this to work with Cloudron (self hosting provider), but I can't save the password, I reckon it is too long (128 bytes). Is it possible to change the config from dat to something readable/maintainable like local/config/database.inc.php? Because sometimes the password changes and then I'll have to sed it via script, which is not much fun with that .dat file.

Best regards, M

**Comment by Kipjr** [comment]
I tried adding a very long password and this is just visible in my data.dat file. Perhaps it has some limitations on your hosting provider. In the future I'm willing to move the configuration in the database instead of data.dat

**Comment by msbt** [comment]
Hey, thanks for getting back to me. It is true, the password gets saved when you enter it, but if you change anything else after that and not include it again, it will be removed. Anyhow, I still can't get in, maybe you've encountered this issue already (errormessages disappear after saving the config the first time):

![LDAP login](http://dev.bits.at/piwigo_ldap.gif)

Error : Binding OK, but no valid DN found on server ...

Other web apps work fine with that ldap information. Any pointers are appreciated.
